server:
  port: 9091
spring:
  application:
    name: service-consumer01

eureka:
  client:
    register-with-eureka: false
    registry-fetch-interval-seconds: 10
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8672/eureka/