server:
  port: 8761 #服务端口


spring:
  application:
    name: eureka-server #应用/服务名称


eureka:
  instance:
    hostname: eureka01 #主机名称，不配置时将根据主机的操作系统来获取
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    client:
      #单机模式必须设置为false
      #register-with-eureka: false #是否将自己注册到注册中心，默认为true
      #fetch-register: false #是否从注册中心获取服务注册信息，默认为true
      service-url:          #注册中心对外暴露的注册地址
        #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
        #设置服务注册中心地址指向另外一个注册中心
        defaultZone: http://localhost:8762/eureka/